apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name  }}
  labels:
    {{- include "simple-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .containerPort }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
  selector:
      app: {{ .Values.app.name }}
